### ISSUE TITLE
Possible code inprovement

### ISSUE THREAD

**Issue by yehorsyrin** [JarvisWise/NCTaskManagerMaven#7]
Please, optimize your code where it is possible.
In some places, even IDEA says there is a way to improve it
![image](https://user-images.githubusercontent.com/23188336/105991098-105b6a80-60ac-11eb-8422-8d7d2168c06c.png)
Also, there are a lot of the same strings, declared many times. It would be better to store them in one place. You can create an enum for them

**Comment by JarvisWise** [comment]
commit c57017565171e6bbffd96ea3d238396f98e35a54
